# Generated by Django 2.2 on 2020-10-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falshfsfse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierunivs',
            name='fil1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premier_choix', to='falshfsfse.Filieres'),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='fil2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_choix', to='falshfsfse.Filieres'),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='fil3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='troisieme_choix', to='falshfsfse.Filieres'),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='institutions', to='falshfsfse.Institutions'),
        ),
    ]
