# Generated by Django 2.2 on 2020-10-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falshfsfse', '0002_auto_20201002_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierunivs',
            name='dipl_etabl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falshfsfse.Mentions'),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='niv_acad',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dossierunivs',
            name='type_diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falshfsfse.TypeDiplomes'),
        ),
    ]
