# Generated by Django 2.2 on 2020-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falshfsfse', '0003_auto_20201002_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierunivs',
            name='serie',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
