# Generated by Django 2.2 on 2020-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falshfsfse', '0004_auto_20201002_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierunivs',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierunivs',
            name='encadreur1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossierunivs',
            name='encadreur2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
